#!/usr/bin/env python
#from pathlib import Path
import datetime

config_data = [
  {
    "max_open_trades": 0,
    "stake_currency": "",
    "stake_amount": 0,
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "timeframe": "2h",
    "use_exit_signal": "true",
    "exit_profit_only": "false",
    "exit_profit_offset": 0,
    "ignore_roi_if_entry_signal": "false",
    "trailing_stop": "false",
    "amend_last_stake_amount": "true",
    "dry_run": "false",
    "unfilledtimeout": {
        "entry": 10,
        "exit": 20
    },
    "entry_pricing": {
        "price_side": "bid",
        "ask_last_balance": 0.0,
        "use_order_book": "true",
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": "true",
            "bids_to_ask_delta": 0
        }
    },
    "order_types": {
        "entry": "limit",
        "exit": "limit",
        "emergency_exit": "market",
        "stoploss": "market",
        "force_exit": "limit",
        "order_time_in_force": {
            "entry": "gtc",
            "exit": "gtc"
        },
        "stoploss_on_exchange": "true",
        "stoploss_on_exchange_interval": 60,
        "stoploss_on_exchange_limit_ratio": 0.99
    },
    "exit_pricing": {
        "price_side": "ask",
        "use_order_book": "true",
        "order_book_top": 1,
        "unfilledtimeout": 1
    },
    "exchange": {
        "name": "",
        "key": "",
        "secret": "",
        "ccxt_config": {
            "enableRateLimit": "true"
            },
        "ccxt_async_config": {
            "enableRateLimit": "true"
        },
        "pair_whitelist": [
            "1INCH/BTC",
            "ACA/BTC",
            "ACH/BTC",
            "ADA/BTC",
            "ADX/BTC",
            "AGLD/BTC",
            "ALGO/BTC",
            "ALPACA/BTC",
            "ALPHA/BTC",
            "ALPINE/BTC",
            "AMB/BTC",
            "AMP/BTC",
            "ANT/BTC",
            "API3/BTC",
            "ARDR/BTC",
            "ARPA/BTC",
            "AST/BTC",
            "ASTR/BTC",
            "ATOM/BTC",
            "AUCTION/BTC",
            "AUDIO/BTC",
            "AVA/BTC",
            "AVAX/BTC",
            "AXS/BTC",
            "BADGER/BTC",
            "BAKE/BTC",
            "BAT/BTC",
            "BEL/BTC",
            "BETA/BTC", 
            "BICO/BTC",
            "BLZ/BTC",
            "BNT/BTC",
            "BOND/BTC",
            "CAKE/BTC",
            "CELO/BTC",
            "CFX/BTC",
            "CHESS/BTC",
            "CHZ/BTC",
            "CITY/BTC",
            "CLV/BTC",
            "BCH/BTC",
            "COTI/BTC",
            "CRV/BTC",
            "CTK/BTC",
            "DASH/BTC",
            "DATA/BTC",
            "DCR/BTC",
            "DEGO/BTC",
            "DGB/BTC",
            "DIA/BTC",
            "DOCK/BTC",
            "DUSK/BTC",
            "ELF/BTC", 
            "ENJ/BTC",
            "ENS/BTC",
            "ETC/BTC",
            "ETH/BTC",
            "FIL/BTC",
            "FIO/BTC",
            "FIRO/BTC",
            "FIS/BTC", 
            "FLM/BTC",
            "FOR/BTC",  
            "FORTH/BTC",
            "FRONT/BTC", 
            "FTM/BTC", 
            "FXS/BTC", 
            "GALA/BTC",
            "GAS/BTC",
            "GLM/BTC",
            "GLMR/BTC",
            "GRT/BTC",
            "GTC/BTC",
            "HARD/BTC",
            "HBAR/BTC",
            "HIGH/BTC",
            "HIVE/BTC",
            "ICP/BTC",
            "ICX/BTC",
            "ILV/BTC",
            "INJ/BTC",
            "IOST/BTC",
            "IOTA/BTC",
            "IOTX/BTC",
            "IRIS/BTC",
            "JOE/BTC", 
            "JST/BTC",
            "KAVA/BTC",
            "KMD/BTC",
            "KNC/BTC",
            "KSM/BTC",
            "LDO/BTC",
            "LINA/BTC",
            "LINK/BTC",
            "LIT/BTC",
            "LOKA/BTC",
            "LPT/BTC",
            "LSK/BTC",
            "LTO/BTC",
            "MANA/BTC",
            "MATIC/BTC",
            "MDT/BTC",
            "MINA/BTC",
            "MKR/BTC", 
            "MOB/BTC",
            "MOVR/BTC",
            "MTL/BTC",
            "MULTI/BTC", 
            "NEO/BTC",
            "NEXO/BTC",
            "NKN/BTC",
            "NULS/BTC",
            "OAX/BTC",
            "OG/BTC",
            "OGN/BTC",
            "OMG/BTC",
            "ONG/BTC",
            "ONT/BTC",
            "ORN/BTC",
            "PEOPLE/BTC",
            "PERP/BTC",
            "PIVX/BTC",
            "POLS/BTC",
            "PORTO/BTC",
            "POWR/BTC", 
            "PROM/BTC",
            "PSG/BTC", 
            "QI/BTC",
            "QNT/BTC",
            "QTUM/BTC", 
            "QUICK/BTC",
            "RAD/BTC",
            "RARE/BTC",
            "REN/BTC",
            "RLC/BTC", 
            "RNDR/BTC",
            "ROSE/BTC",
            "RUNE/BTC",
            "SAND/BTC",
            "SCRT/BTC", 
            "SFP/BTC", 
            "SNM/BTC",
            "SNT/BTC",
            "SOL/BTC",
            "SSV/BTC",
            "STEEM/BTC",
            "STORJ/BTC",
            "STPT/BTC",
            "STRAX/BTC",
            "SUPER/BTC",
            "SUSHI/BTC",
            "SXP/BTC",
            "SYS/BTC",
            "TFUEL/BTC",
            "THETA/BTC",
            "TKO/BTC",
            "TOMO/BTC",
            "TRB/BTC",
            "TRX/BTC",
            "TVK/BTC",
            "TWT/BTC",
            "UMA/BTC",
            "UNFI/BTC",
            "UNI/BTC",
            "UTK/BTC",
            "VIB/BTC",
            "VIDT/BTC",
            "VOXEL/BTC",
            "WAN/BTC",
            "WAVES/BTC",
            "WAXP/BTC",
            "WING/BTC",
            "WTC/BTC",
            "XLM/BTC",
            "XMR/BTC",
            "XNO/BTC",
            "XRP/BTC",
            "XTZ/BTC",
            "XVS/BTC",
            "YFI/BTC",
            "YGG/BTC",
            "ZEC/BTC",
            "ZEN/BTC",
            "ZRX/BTC"


        ],
        "pair_blacklist": [
            "BNB/BUSD",
            "BNB/ETH",
            "BNB/EUR",
            "BNB/NGN",
            "BNB/PAX",
            "BNB/RUB",
            "BNB/TRY",
            "BNB/TUSD",
            "BNB/USDC",
            "BNB/USDS",
            "BNB/USDT",
        ]
    },
    "pairlists": [
        {"method": "StaticPairList"},
        {"method": "PriceFilter", "low_price_ratio": 0.20},
        {"method": "ShuffleFilter", "seed": 42}
    ],
    "edge": {
        "enabled": "false",
        "process_throttle_secs": 3600,
        "calculate_since_number_of_days": 7,
        "allowed_risk": 0,
        "stoploss_range_min": -0.40,
        "stoploss_range_max": -0.401,
        "stoploss_range_step": -0.001,
        "minimum_winrate": -0.99,
        "minimum_expectancy": -0.99,
        "min_trade_number": 1,
        "max_trade_duration_minute": 1440,
        "remove_pumps": "false"
    },
    "telegram": {
        "enabled": "true",
        "token": "",
        "chat_id": "",
        "notification_settings": {
        "status": "on",
        "warning": "on",
        "startup": "on",
        "entry": "on",
        "exit": "on",
        "entry_cancel": "on",
        "exit_cancel": "on"
        }
    },
    "api_server": {
        "enabled": "false",
        "listen_ip_address": "",
        "listen_port": 8080,
        "verbosity": "info",
        "jwt_secret_key": "",
        "CORS_origins": [],
        "username": "",
        "password": ""
    },
    "bot_name": "",
    "db_url": "",
    "initial_state": "running",
    "force_entry_enable": "true",
    "internals": {
        "process_throttle_secs": 5,
        "heartbeat_interval": 60
    },
    "disable_dataframe_checks": "false",
    "strategy": "",
    "strategy_path": "",
    "dataformat_ohlcv": "json",
    "dataformat_trades": "jsongz"
  },

  {
    "max_open_trades": 0,
    "stake_currency": "",
    "stake_amount": 0,
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "timeframe": "2h",
    "use_exit_signal": "true",
    "exit_profit_only": "false",
    "ignore_roi_if_entry_signal": "false",
    "trailing_stop": "false",
    "amend_last_stake_amount": "true",
    "dry_run": "false",
    "unfilledtimeout": {
        "entry": 10,
        "exit": 20
    },
    "entry_pricing": {
        "price_side": "bid",
        "ask_last_balance": 0.0,
        "use_order_book": "true",
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": "true",
            "bids_to_ask_delta": 0
        }
    },
    "order_types": {
        "entry": "limit",
        "exit": "limit",
        "emergency_exit": "market",
        "stoploss": "market",
        "order_time_in_force": {
            "entry": "gtc",
            "exit": "gtc"
        },
        "stoploss_on_exchange": "true",
        "stoploss_on_exchange_interval": 60,
        "stoploss_on_exchange_limit_ratio": 0.99
    },
    "exit_pricing": {
        "price_side": "ask",
        "use_order_book": "true",
        "order_book_top": 1,
        "unfilledtimeout": 1
    },
    "exchange": {
        "name": "",
        "key": "",
        "secret": "",
        "ccxt_config": {"enableRateLimit": "true"},
        "ccxt_async_config": {
            "enableRateLimit": "true"
        },
        "pair_whitelist": [
            "AAVE/ETH",
            "ADX/ETH",
            "ALGO/ETH",
            "BAT/ETH",
            "BETA/ETH",
            "BNB/ETH",
            "BNT/ETH",
            "CRV/ETH",
            "DASH/ETH",
            "DENT/ETH",
            "DEXE/ETH",
            "DOT/ETH",
            "EGLD/ETH",
            "ELF/ETH",
            "ENJ/ETH",
            "FTM/ETH",
            "FUN/ETH",
            "GAL/ETH",
            "GALA/ETH",
            "HOT/ETH",
            "IOST/ETH",
            "IOTA/ETH",
            "IOTX/ETH",
            "JASMY/ETH",
            "KAVA/ETH",
            "LSK/ETH",
            "LTC/ETH",
            "MATIC/ETH",
            "MTL/ETH",
            "NEAR/ETH",
            "OMG/ETH",
            "OP/ETH",
            "POWR/ETH",
            "PROS/ETH",
            "PUNDIX/ETH",
            "QKC/ETH",
            "QTUM/ETH",
            "RLC/ETH",
            "ROSE/ETH",
            "SAND/ETH",
            "SC/ETH",
            "SCRT/ETH",
            "SNT/ETH",
            "SSV/ETH",
            "THETA/ETH",
            "TRX/ETH",
            "UFT/ETH",
            "UNI/ETH",
            "VIB/ETH",
            "WAN/ETH",
            "WAVES/ETH",
            "XLM/ETH",
            "XMR/ETH",
            "XTZ/ETH",
            "XVG/ETH",
            "ZEC/ETH",
            "ZEN/ETH",
            "ZIL/ETH"


        ],
        "pair_blacklist": [
            "ETH/BUSD",
            "ETH/EUR",
            "ETH/NGN",
            "ETH/PAX",
            "ETH/RUB",
            "ETH/TRY",
            "ETH/TUSD",
            "ETH/USDC",
            "ETH/USDS"
        ]
    },
    "pairlists": [
        {"method": "StaticPairList"},
        {"method": "PriceFilter"},
        {"method": "ShuffleFilter", "seed": 42}
    ],
    "edge": {
        "enabled": "false",
        "process_throttle_secs": 3600,
        "calculate_since_number_of_days": 7,
        "allowed_risk": 0,
        "stoploss_range_min": -0.40,
        "stoploss_range_max": -0.401,
        "stoploss_range_step": -0.001,
        "minimum_winrate": -0.99,
        "minimum_expectancy": -0.99,
        "min_trade_number": 1,
        "max_trade_duration_minute": 1440,
        "remove_pumps": "false"
    },
    "telegram": {
        "enabled": "true",
        "token": "",
        "chat_id": "",
        "notification_settings": {
        "status": "on",
        "warning": "on",
        "startup": "on",
        "entry": "on",
        "exit": "on",
        "entry_cancel": "on",
        "exit_cancel": "on"
        }
    },
    "api_server": {
        "enabled": "false",
        "listen_ip_address": "",
        "listen_port": 8080,
        "verbosity": "info",
        "jwt_secret_key": "",
        "CORS_origins": [],
        "username": "",
        "password": ""
    },
    "bot_name": "",
    "db_url": "",
    "initial_state": "running",
    "force_entry_enable": "true",
    "internals": {
        "process_throttle_secs": 5,
        "heartbeat_interval": 60
    },
    "disable_dataframe_checks": "false",
    "strategy": "",
    "strategy_path": "",
    "dataformat_ohlcv": "json",
    "dataformat_trades": "jsongz"
  },
  {
    "max_open_trades": 0,
    "stake_currency": "",
    "stake_amount": 0,
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "timeframe": "2h",
    "use_exit_signal": "true",
    "exit_profit_only": "false",
    "ignore_roi_if_entry_signal": "false",
    "trailing_stop": "false",
    "amend_last_stake_amount": "true",
    "dry_run": "false",
    "position_adjustment_enable": "true",
    "unfilledtimeout": {
        "entry": 10,
        "exit": 20
    },
    "entry_pricing": {
        "price_side": "bid",
        "ask_last_balance": 0.0,
        "use_order_book": "true",
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": "true",
            "bids_to_ask_delta": 0
        }
    },
    "order_types": {
        "entry": "limit",
        "exit": "limit",
        "emergency_exit": "market",
        "stoploss": "market",
        "order_time_in_force": {
            "entry": "gtc",
            "exit": "gtc"
        } ,
        "stoploss_on_exchange": "true",
        "stoploss_on_exchange_interval": 60,
        "stoploss_on_exchange_limit_ratio": 0.99
    },
    "exit_pricing": {
        "price_side": "ask",
        "use_order_book": "true",
        "order_book_top": 1,
        "unfilledtimeout": 1
    },
    "exchange": {
        "name": "",
        "key": "",
        "secret": "",
        "ccxt_config": {"enableRateLimit": "true"},
        "ccxt_async_config": {
            "enableRateLimit": "true"
        },
        "pair_whitelist": [
            "1INCH/USDT",
            "AAVE/USDT",
            "ACM/USDT",
            "ADA/USDT",
            "ADADOWN/USDT",
            "ADAUP/USDT",
            "AGLD/USDT",
            "ALGO/USDT",
            "ALICE/USDT",
            "ALPHA/USDT",
            "ALPINE/USDT",
            "ANKR/USDT",
            "ANT/USDT",
            "AR/USDT",
            "ARDR/USDT",
            "ARPA/USDT",
            "ASR/USDT",
            "ASTR/USDT",
            "ATA/USDT",
            "ATM/USDT",
            "ATOM/USDT",
            "AUDIO/USDT",
            "AVA/USDT",
            "AVAX/USDT",
            "AXS/USDT",
            "BADGER/USDT",
            "BAKE/USDT",
            "BAL/USDT",
            "BAND/USDT",
            "BAR/USDT",
            "BAT/USDT",
            "BCH/USDT",
            "BEL/USDT",
            "BETA/USDT",
            "BICO/USDT",
            "BIFI/USDT",
            "BLZ/USDT",
            "BNB/USDT",
            "BNBDOWN/USDT",
            "BNBUP/USDT",
            "BNT/USDT",
            "BNX/USDT",
            "BOND/USDT",
            "BTC/USDT",
            "BTCDOWN/USDT",
            "BTCUP/USDT",
            "BTS/USDT",
            "BTTC/USDT",
            "C98/USDT",
            "CAKE/USDT",
            "CELO/USDT",
            "CELR/USDT",
            "CHR/USDT",
            "CHZ/USDT",
            "CLV/USDT",
            "COMP/USDT",
            "COS/USDT",
            "COTI/USDT",
            "CRV/USDT",
            "CTK/USDT",
            "CTSI/USDT",
            "CTXC/USDT",
            "CVP/USDT",
            "DAR/USDT",
            "DASH/USDT",
            "DATA/USDT",
            "DEGO/USDT",
            "DENT/USDT",
            "DF/USDT",
            "DGB/USDT",
            "DIA/USDT",
            "DOCK/USDT",
            "DOGE/USDT",
            "DOT/USDT",
            "DREP/USDT",
            "DUSK/USDT",
            "EGLD/USDT",
            "ELF/USDT",
            "ENJ/USDT",
            "ENS/USDT",
            "EOS/USDT",
            "EPX/USDT",
            "ERN/USDT",
            "ETC/USDT",
            "ETH/USDT",
            "ETHDOWN/USDT",
            "ETHUP/USDT",
            "FET/USDT",
            "FIDA/USDT",
            "FIL/USDT",
            "FIO/USDT",
            "FIRO/USDT",
            "FLM/USDT",
            "FLOW/USDT",
            "FOR/USDT",
            "FORTH/USDT",
            "FRONT/USDT",
            "FTM/USDT",
            "FUN/USDT",
            "FXS/USDT",
            "GALA/USDT",
            "GMX/USDT",
            "GNO/USDT",
            "GRT/USDT",
            "GTC/USDT",
            "HARD/USDT",
            "HBAR/USDT",
            "HFT/USDT",
            "HIFI/USDT",
            "HIGH/USDT",
            "HIVE/USDT",
            "HOT/USDT",
            "ICX/USDT",
            "ILV/USDT",
            "IMX/USDT",
            "INJ/USDT",
            "IOST/USDT",
            "IOTA/USDT",
            "IRIS/USDT",
            "JOE/USDT",
            "JST/USDT",
            "JUV/USDT",
            "KAVA/USDT",
            "KDA/USDT",
            "KLAY/USDT",
            "KMD/USDT",
            "KNC/USDT",
            "KSM/USDT",
            "LDO/USDT",
            "LINK/USDT",
            "LIT/USDT",
            "LOKA/USDT",
            "LPT/USDT",
            "LSK/USDT",
            "LTC/USDT",
            "LTO/USDT",
            "LUNA/USDT",
            "MANA/USDT",
            "MATIC/USDT",
            "MBL/USDT",
            "MBOX/USDT",
            "MC/USDT",
            "MDX/USDT",
            "MINA/USDT",
            "MKR/USDT",
            "MLN/USDT",
            "MOB/USDT",
            "MTL/USDT",
            "NEAR/USDT",
            "NEO/USDT",
            "NKN/USDT",
            "NMR/USDT",
            "NULS/USDT",
            "OCEAN/USDT",
            "OG/USDT",
            "OGN/USDT",
            "OM/USDT",
            "OMG/USDT",
            "ONE/USDT",
            "ONG/USDT",
            "ONT/USDT",
            "OOKI/USDT",
            "OP/USDT",
            "OXT/USDT",
            "PERL/USDT",
            "PERP/USDT",
            "PHA/USDT",
            "PLA/USDT",
            "PNT/USDT",
            "POLS/USDT",
            "POND/USDT",
            "PORTO/USDT",
            "PSG/USDT",
            "PUNDIX/USDT",
            "PYR/USDT",
            "QNT/USDT",
            "QTUM/USDT",
            "RARE/USDT",
            "REN/USDT",
            "RIF/USDT",
            "RLC/USDT",
            "RNDR/USDT",
            "ROSE/USDT",
            "RSR/USDT",
            "SAND/USDT",
            "SC/USDT",
            "SCRT/USDT",
            "SFP/USDT",
            "SHIB/USDT",
            "SKL/USDT",
            "SNX/USDT",
            "SOL/USDT",
            "STMX/USDT",
            "STORJ/USDT",
            "STPT/USDT",
            "STRAX/USDT",
            "STX/USDT",
            "SUPER/USDT",
            "SUSHI/USDT",
            "SXP/USDT",
            "TFUEL/USDT",
            "THETA/USDT",
            "TLM/USDT",
            "TOMO/USDT",
            "TRB/USDT",
            "TROY/USDT",
            "TRU/USDT",
            "TRX/USDT",
            "TVK/USDT",
            "TWT/USDT",
            "UMA/USDT",
            "UNFI/USDT",
            "UNI/USDT",
            "UTK/USDT",
            "VET/USDT",
            "VITE/USDT",
            "VOXEL/USDT",
            "VTHO/USDT",
            "WAN/USDT",
            "WAVES/USDT",
            "WAXP/USDT",
            "WIN/USDT",
            "WING/USDT",
            "WNXM/USDT",
            "WOO/USDT",
            "WRX/USDT",
            "WTC/USDT",
            "XEC/USDT",
            "XLM/USDT",
            "XMR/USDT",
            "XRP/USDT",
            "XRPDOWN/USDT",
            "XRPUP/USDT",
            "XTZ/USDT",
            "XVG/USDT",
            "YFI/USDT",
            "YFII/USDT",
            "YGG/USDT",
            "ZEC/USDT",
            "ZEN/USDT",
            "ZIL/USDT",
            "ZRX/USDT"


        ],
        "pair_blacklist": [
            "ETH/BUSD",
            "ETH/EUR",
            "ETH/NGN",
            "ETH/PAX",
            "ETH/RUB",
            "ETH/TRY",
            "ETH/TUSD",
            "ETH/USDC",
            "ETH/USDS"
        ]
    },
    "pairlists": [
        {"method": "StaticPairList"},
        {"method": "PriceFilter"},
        {"method": "ShuffleFilter", "seed": 42}
    ],
    "edge": {
        "enabled": "false",
        "process_throttle_secs": 3600,
        "calculate_since_number_of_days": 7,
        "allowed_risk": 0,
        "stoploss_range_min": -0.40,
        "stoploss_range_max": -0.401,
        "stoploss_range_step": -0.001,
        "minimum_winrate": -0.99,
        "minimum_expectancy": -0.99,
        "min_trade_number": 1,
        "max_trade_duration_minute": 1440,
        "remove_pumps": "false"
    },
    "telegram": {
        "enabled": "",
        "token": "",
        "chat_id": "",
        "notification_settings": {
        "status": "on",
        "warning": "on",
        "startup": "on",
        "entry": "on",
        "exit": "on",
        "entry_cancel": "on",
        "exit_cancel": "on"
        }
    },
    "api_server": {
        "enabled": "false",
        "listen_ip_address": "",
        "listen_port": 8080,
        "verbosity": "info",
        "jwt_secret_key": "",
        "CORS_origins": [],
        "username": "",
        "password": ""
    },
    "bot_name": "",
    "db_url": "",
    "initial_state": "running",
    "force_entry_enable": "true",
    "internals": {
        "process_throttle_secs": 5,
        "heartbeat_interval": 60
    },
    "disable_dataframe_checks": "false",
    "strategy": "",
    "strategy_path": "",
    "dataformat_ohlcv": "json",
    "dataformat_trades": "jsongz"
  },
  {
    "max_open_trades": 0,
    "stake_currency": "",
    "stake_amount": 0,
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "timeframe": "2h",
    "use_exit_signal": "true",
    "exit_profit_only": "false",
    "ignore_roi_if_entry_signal": "false",
    "trailing_stop": "false",
    "amend_last_stake_amount": "true",
    "dry_run": "false",
    "unfilledtimeout": {
        "entry": 10,
        "exit": 20
    },
    "entry_pricing": {
        "price_side": "bid",
        "ask_last_balance": 0.0,
        "use_order_book": "true",
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": "true",
            "bids_to_ask_delta": 0
        }
    },
    "order_types": {
        "entry": "limit",
        "exit": "limit",
        "emergency_exit": "market",
        "stoploss": "market",
        "order_time_in_force": {
            "entry": "gtc",
            "exit": "gtc"
        },
        "stoploss_on_exchange": "true",
        "stoploss_on_exchange_interval": 60,
        "stoploss_on_exchange_limit_ratio": 0.99
    },
    "exit_pricing": {
        "price_side": "ask",
        "use_order_book": "true",
        "order_book_top": 1,
        "unfilledtimeout": 1
    },
    "exchange": {
        "name": "",
        "key": "",
        "secret": "",
        "ccxt_config": {
            "enableRateLimit": "true"
            },
        "ccxt_async_config": {
            "enableRateLimit": "true"
        },
        "pair_whitelist": [
            "ADA/BNB",
            "ALGO/BNB",
            "ALICE/BNB",
            "ANKR/BNB",
            "ANT/BNB",
            "AR/BNB",
            "ARPA/BNB",
            "ATOM/BNB",
            "AXS/BNB",
            "BEL/BNB",
            "BETA/BNB",
            "CAKE/BNB",
            "CELR/BNB",
            "CHR/BNB",
            "CHZ/BNB",
            "COCOS/BNB",
            "COS/BNB",
            "COTI/BNB",
            "CTK/BNB",
            "CTSI/BNB",
            "DAR/BNB",
            "DASH/BNB",
            "DOT/BNB",
            "DYDX/BNB",
            "EGLD/BNB",
            "ENJ/BNB",
            "EOS/BNB",
            "ETC/BNB",
            "FET/BNB",
            "FIL/BNB",
            "FTM/BNB",
            "FUN/BNB",
            "GAL/BNB",
            "GLMR/BNB",
            "HARD/BNB",
            "HBAR/BNB",
            "HIGH/BNB",
            "IDEX/BNB",
            "INJ/BNB",
            "IOTA/BNB",
            "KAVA/BNB",
            "KP3R/BNB",
            "LINK/BNB",
            "LOKA/BNB",
            "LPT/BNB",
            "LRC/BNB",
            "LTC/BNB",
            "MASK/BNB",
            "MATIC/BNB",
            "MBOX/BNB",
            "MINA/BNB",
            "NEAR/BNB",
            "NEO/BNB",
            "OCEAN/BNB",
            "ONE/BNB",
            "OP/BNB",
            "PEOPLE/BNB",
            "POLS/BNB",
            "QNT/BNB",
            "RAD/BNB",
            "RAY/BNB",
            "RSR/BNB",
            "RUNE/BNB",
            "SAND/BNB",
            "SNX/BNB",
            "SOL/BNB",
            "STX/BNB",
            "SUSHI/BNB",
            "SXP/BNB",
            "THETA/BNB",
            "TRX/BNB",
            "VET/BNB",
            "VOXEL/BNB",
            "WAVES/BNB",
            "WAXP/BNB",
            "WIN/BNB",
            "WOO/BNB",
            "WRX/BNB",
            "XLM/BNB",
            "XTZ/BNB",
            "XVS/BNB",
            "YGG/BNB",
            "ZEC/BNB",
            "ZIL/BNB"

        ],
        "pair_blacklist": [
            "BNB/BUSD",
            "BNB/ETH",
            "BNB/EUR",
            "BNB/NGN",
            "BNB/PAX",
            "BNB/RUB",
            "BNB/TRY",
            "BNB/TUSD",
            "BNB/USDC",
            "BNB/USDS",
            "BNB/USDT",
        ]
    },
    "pairlists": [
        {"method": "StaticPairList"},
        {"method": "PriceFilter"},
        {"method": "ShuffleFilter", "seed": 42}
    ],
    "edge": {
        "enabled": "false",
        "process_throttle_secs": 3600,
        "calculate_since_number_of_days": 7,
        "allowed_risk": 0,
        "stoploss_range_min": -0.40,
        "stoploss_range_max": -0.401,
        "stoploss_range_step": -0.001,
        "minimum_winrate": -0.99,
        "minimum_expectancy": -0.99,
        "min_trade_number": 1,
        "max_trade_duration_minute": 1440,
        "remove_pumps": "false"
    },
    "telegram": {
        "enabled": "true",
        "token": "",
        "chat_id": "",
        "notification_settings": {
        "status": "on",
        "warning": "on",
        "startup": "on",
        "envry": "on",
        "exit": "on",
        "entry_cancel": "on",
        "exit_cancel": "on"
        }
    },
    "api_server": {
        "enabled": "false",
        "listen_ip_address": "",
        "listen_port": 8080,
        "verbosity": "info",
        "jwt_secret_key": "",
        "CORS_origins": [],
        "username": "",
        "password": ""
    },
    "bot_name": "",
    "db_url": "",
    "initial_state": "running",
    "force_entry_enable": "true",
    "internals": {
        "process_throttle_secs": 5,
        "heartbeat_interval": 60
    },
    "disable_dataframe_checks": "false",
    "strategy": "",
    "strategy_path": "",
    "dataformat_ohlcv": "json",
    "dataformat_trades": "jsongz"
  },
  {
    "max_open_trades": 0,
    "stake_currency": "",
    "stake_amount": 0,
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "timeframe": "2h",
    "use_exit_signal": "true",
    "exit_profit_only": "false",
    "exit_profit_offset": 0.0,
    "ignore_roi_if_entry_signal": "false",
    "trailing_stop": "false",
    "amend_last_stake_amount": "false",
    "dry_run": "false",
    "position_adjustment_enable": "true",
    "trading_mode": "futures",
    "margin_mode": "isolated",
    "unfilledtimeout": {
        "entry": 10,
        "exit": 20
    },
    "entry_pricing": {
        "price_side": "same",
        "ask_last_balance": 0.0,
        "use_order_book": "true",
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": "true",
            "bids_to_ask_delta": 0
        }
    },
    "order_types": {
        "entry": "limit",
        "exit": "limit",
        "emergency_exit": "market",
        "force_exit": "market",
        "force_entry": "market",
        "stoploss": "market",
        "stoploss_on_exchange": "true",
        "stoploss_on_exchange_interval": 60,
        "stoploss_on_exchange_limit_ratio": 0.99
    },
    "order_time_in_force": {
        "entry": "gtc",
        "exit": "gtc"
    },
    "exit_pricing": {
        "price_side": "same",
        "use_order_book": "true",
        "order_book_top": 1,
        "unfilledtimeout": 1
    },
    "exchange": {
        "name": "",
        "key": "",
        "secret": "",
        "ccxt_config": {},
        "ccxt_async_config": {},
        "pair_whitelist": [
            "1INCH/USDT:USDT",
            "ALICE/USDT:USDT",
            "ALPHA/USDT:USDT",
            "AR/USDT:USDT",
            "AVAX/USDT:USDT",
            "AXS/USDT:USDT",
            "BAND/USDT:USDT",
            "BEL/USDT:USDT",
            "BLZ/USDT:USDT",
            "C98/USDT:USDT",
            "CELO/USDT:USDT",
            "CHZ/USDT:USDT",
            "CRV/USDT:USDT",
            "CTK/USDT:USDT",
            "CTSI/USDT:USDT",
            "DOGE/USDT:USDT",
            "DUSK/USDT:USDT",
            "DYDX/USDT:USDT",
            "ENJ/USDT:USDT",
            "ENS/USDT:USDT",
            "EOS/USDT:USDT",
            "FLM/USDT:USDT",
            "GAL/USDT:USDT",
            "GALA/USDT:USDT",
            "GRT/USDT:USDT",
            "HBAR/USDT:USDT",
            "HOT/USDT:USDT",
            "ICX/USDT:USDT",
            "IOST/USDT:USDT",
            "KAVA/USDT:USDT",
            "KNC/USDT:USDT",
            "KSM/USDT:USDT",
            "LINA/USDT:USDT",
            "LIT/USDT:USDT",
            "LRC/USDT:USDT",
            "MANA/USDT:USDT",
            "MKR/USDT:USDT",
            "MTL/USDT:USDT",
            "NEAR/USDT:USDT",
            "NEO/USDT:USDT",
            "NKN/USDT:USDT",
            "OCEAN/USDT:USDT",
            "OGN/USDT:USDT",
            "ONE/USDT:USDT",
            "PEOPLE/USDT:USDT",
            "QTUM/USDT:USDT",
            "REEF/USDT:USDT",
            "RLC/USDT:USDT",
            "RSR/USDT:USDT",
            "RVN/USDT:USDT",
            "SKL/USDT:USDT",
            "SOL/USDT:USDT",
            "STMX/USDT:USDT",
            "STORJ/USDT:USDT",
            "SUSHI/USDT:USDT",
            "SXP/USDT:USDT",
            "TOMO/USDT:USDT",
            "TRB/USDT:USDT",
            "UNFI/USDT:USDT",
            "UNI/USDT:USDT",
            "VET/USDT:USDT",
            "WAVES/USDT:USDT",
            "WOO/USDT:USDT",
            "XLM/USDT:USDT",
            "XMR/USDT:USDT",
            "XTZ/USDT:USDT",
            "ZEC/USDT:USDT",
            "ZIL/USDT:USDT"


        ],
        "pair_blacklist": [
            "TUSD/USDT:USDT",
            "USDC/USDT:USDT",
            "USDS/USDT:USDT",
            "BUSD/USDT:USDT"
        ]
    },
    "pairlists": [
        {"method": "StaticPairList"},
        {"method": "PriceFilter"},
        {"method": "ShuffleFilter", "seed": 42}
    ],
    "edge": {
        "enabled": "false",
        "process_throttle_secs": 3600,
        "calculate_since_number_of_days": 7,
        "allowed_risk": 0,
        "stoploss_range_min": -0.40,
        "stoploss_range_max": -0.401,
        "stoploss_range_step": -0.001,
        "minimum_winrate": -0.99,
        "minimum_expectancy": -0.99,
        "min_trade_number": 1,
        "max_trade_duration_minute": 1440,
        "remove_pumps": "false"
    },
    "telegram": {
        "enabled": "",
        "token": "",
        "chat_id": "",
        "notification_settings": {
        "status": "on",
        "warning": "on",
        "startup": "on",
        "entry": "on",
        "exit": "on",
        "entry_cancel": "on",
        "exit_cancel": "on"
        }
    },
    "api_server": {
        "enabled": "false",
        "listen_ip_address": "",
        "listen_port": 8080,
        "verbosity": "info",
        "jwt_secret_key": "",
        "CORS_origins": [],
        "username": "",
        "password": ""
    },
    "bot_name": "",
    "db_url": "",
    "initial_state": "running",
    "force_entry_enable": "true",
    "internals": {
        "process_throttle_secs": 5,
        "heartbeat_interval": 60
    },
    "disable_dataframe_checks": "false",
    "strategy": "",
    "strategy_path": "",
    "dataformat_ohlcv": "json",
    "dataformat_trades": "jsongz"
  }
]
